# Generated by Django 6.0.5 on 2026-06-18 09:54

import django.core.validators
import django.db.models.deletion
import myria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='cars_photos/', verbose_name='Головне фото')),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Додати відео з YouTube')),
                ('transport_type', models.CharField(choices=[('Легкові', 'Легкові'), ('Мото', 'Мото'), ('Вантажівки', 'Вантажівки'), ('Причепи', 'Причепи'), ('Спецтехніка', 'Спецтехніка'), ('Сільгосптехніка', 'Сільгосптехніка'), ('Автобуси', 'Автобуси'), ('Водний транспорт', 'Водний транспорт'), ('Повітряний транспорт', 'Повітряний транспорт'), ('Автобудинки', 'Автобудинки')], max_length=50, verbose_name='Тип транспорту')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка авто')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(myria.models.current_year)], verbose_name='Рік випуску')),
                ('mileage', models.IntegerField(verbose_name='Пробіг (тис. км)')),
                ('body_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кузова')),
                ('modification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модифікація')),
                ('region', models.CharField(choices=[('Київ', 'Київ'), ('Вінниця', 'Вінниця'), ('Кропивницький', 'Кропивницький (Кіровоград)'), ('Полтава', 'Полтава'), ('Черкаси', 'Черкаси'), ('Тернопіль', 'Тернопіль'), ('Хмельницький', 'Хмельницький'), ('Львів', 'Львів'), ('Рівне', 'Рівне'), ('Івано-Франківськ', 'Івано-Франківськ'), ('Луцьк', 'Луцьк'), ('Ужгород', 'Ужгород'), ('Чернівці', 'Чернівці'), ('Харків', 'Харків'), ('Дніпро', 'Дніпро (Дніпропетровськ)'), ('Донецька обл.', 'Донецька обл.'), ('Запоріжжя', 'Запоріжжя'), ('Одеса', 'Одеса'), ('Миколаїв', 'Миколаїв'), ('Херсон', 'Херсон'), ('Житомир', 'Житомир'), ('Чернігів', 'Чернігів'), ('Суми', 'Суми')], max_length=50, verbose_name='Регіон')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('vin_code', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN-код')),
                ('is_owner', models.BooleanField(default=True, verbose_name='Ви власник авто?')),
                ('description', models.TextField(max_length=2000, verbose_name='Опис автомобіля')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('imported_from', models.CharField(blank=True, choices=[('Австралія', 'Австралія'), ('Австрія', 'Австрія'), ('Алжир', 'Алжир'), ('Англія', 'Англія'), ('Аргентина', 'Аргентина'), ('Бельгія', 'Бельгія'), ('Білорусь', 'Білорусь'), ('Болгарія', 'Болгарія'), ('Бразилія', 'Бразилія'), ('Греція', 'Греція'), ('Грузія', 'Грузія'), ('Данія', 'Данія'), ('Естонія', 'Естонія'), ('Єгипет', 'Єгипет'), ('Ізраїль', 'Ізраїль'), ('Індія', 'Індія'), ('Іран', 'Іран'), ('Ірландія', 'Ірландія'), ('Ісландія', 'Ісландія'), ('Іспанія', 'Іспанія'), ('Італія', 'Італія'), ('Казахстан', 'Казахстан'), ('Канада', 'Канада'), ('Китай', 'Китай'), ('Корея', 'Корея'), ('Латвія', 'Латвія'), ('Литва', 'Литва'), ('Люксембург', 'Люксембург'), ('Малайзія', 'Малайзія'), ('Молдова', 'Молдова'), ('Монако', 'Монако'), ('Нідерланди', 'Нідерланди'), ('Німеччина', 'Німеччина'), ('Норвегія', 'Норвегія'), ('ОАЕ', 'ОАЕ'), ('Польша', 'Польща'), ('Португалiя', 'Португалія'), ('Румунія', 'Румунія'), ('Сербія', 'Сербія'), ('Словаччина', 'Словаччина'), ('Словенія', 'Словенія'), ('США', 'США'), ('Таджикистан', 'Таджикистан'), ('Таїланд', 'Таїланд'), ('Тайвань', 'Тайвань'), ('Туреччина', 'Туреччина'), ('Угорщина', 'Угорщина'), ('Узбекистан', 'Узбекистан'), ('Фінляндія', 'Фінляндія'), ('Франція', 'Франція'), ('Хорватія', 'Хорватія'), ('Чехія', 'Чехія'), ('Швейцарія', 'Швейцарія'), ('Швеція', 'Швеція'), ('Японія', 'Японія')], max_length=50, null=True, verbose_name='Пригнаний з')),
                ('accident', models.CharField(blank=True, choices=[('Ні, не був у ДТП', 'Ні, не був у ДТП'), ('Так, був у ДТП', 'Так, був у ДТП')], max_length=50, null=True, verbose_name='Участь в ДТП')),
                ('paintwork', models.CharField(blank=True, max_length=100, null=True, verbose_name='Лакофарбове покриття')),
                ('technical_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Технічний стан')),
                ('conditioner', models.CharField(blank=True, choices=[('Кондиціонер', 'Кондиціонер'), ('Клімат-контроль 1-зонний', 'Клімат-контроль 1-зонний'), ('Клімат-контроль 2-зонний', 'Клімат-контроль 2-зонний'), ('Клімат-контроль багатозонний', 'Клімат-контроль багатозонний')], max_length=50, null=True, verbose_name='Кондиціонер')),
                ('windows', models.CharField(blank=True, choices=[('Передні', 'Передні'), ('Передні та задні', 'Передні та задні')], max_length=50, null=True, verbose_name='Електросклопідйомники')),
                ('interior_material', models.CharField(blank=True, choices=[('Тканина', 'Тканина'), ('Шкіра', 'Шкіра'), ('Велюр', 'Велюр'), ('Комбінований', 'Комбінований'), ('Штучна шкіра', 'Штучна шкіра'), ('Алькантара', 'Алькантара')], max_length=50, null=True, verbose_name='Матеріали салону')),
                ('interior_color', models.CharField(blank=True, choices=[('Світлий', 'Світлий'), ('Темний', 'Темний'), ('Коричневий', 'Коричневий')], max_length=50, null=True, verbose_name='Колір салону')),
                ('steering_assist', models.CharField(blank=True, choices=[('Гідро', 'Гідро'), ('Електро', 'Електро')], max_length=50, null=True, verbose_name='Підсилювач керма')),
                ('steering_adjustment', models.CharField(blank=True, choices=[('По висоті', 'По висоті'), ('По висоті та по вильоту', 'По висоті та по вильоту')], max_length=50, null=True, verbose_name='Регулювання керма')),
                ('spare_wheel', models.CharField(blank=True, choices=[('Повнорозмірне', 'Повнорозмірне'), ('Докатка', 'Докатка')], max_length=50, null=True, verbose_name='Запасне колесо')),
                ('headlights', models.CharField(blank=True, choices=[('Ксенонові/Біксенонові', 'Ксенонові/Біксенонові'), ('Лазерні', 'Лазерні'), ('Світлодіодні', 'Світлодіодні'), ('Матричні', 'Матричні'), ('Галогенні', 'Галогенні')], max_length=50, null=True, verbose_name='Фари')),
                ('seat_height', models.CharField(blank=True, choices=[('Ручне регулювання сидіння водія', 'Ручне регулювання сидіння водія'), ('Ручне регулювання передніх сидінь', 'Ручне регулювання передніх сидінь'), ('Електрорегулювання сидіння водія', 'Електрорегулювання сидіння водія'), ('Електрорегулювання передніх сидінь', 'Електрорегулювання передніх сидінь'), ('Електрорегулювання передніх та задніх сидінь', 'Електрорегулювання передніх та задніх сидінь')], max_length=50, null=True, verbose_name='Регулювання сидінь по висоті')),
                ('seat_memory', models.CharField(blank=True, choices=[('Сидіння водія', 'Сидіння водія'), ('Передні сидіння', 'Передні сидіння'), ('Передні та задні сидіння', 'Передні та задні сидіння')], max_length=50, null=True, verbose_name="Пам'ять положення сидіння")),
                ('seat_heating', models.CharField(blank=True, choices=[('Передні сидіння', 'Передні сидіння'), ('Передні та задні сидіння', 'Передні та задні сидіння')], max_length=50, null=True, verbose_name='Підігрів сидінь')),
                ('seat_ventilation', models.CharField(blank=True, choices=[('Передні сидіння', 'Передні сидіння'), ('Передні та задні сидіння', 'Передні та задні сидіння')], max_length=50, null=True, verbose_name='Вентиляція сидінь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('грн.', 'грн.')], default='$', max_length=10, verbose_name='Валюта')),
                ('bargain_possible', models.BooleanField(default=False, verbose_name='Торг')),
                ('exchange_possible', models.BooleanField(default=False, verbose_name='Обмін')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='Посилання на додаткове фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myria.car')),
            ],
            options={
                'verbose_name': 'Додаткове фото',
                'verbose_name_plural': 'Додаткові фото',
            },
        ),
    ]
