# Generated by Django 6.0.5 on 2026-06-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('price', models.IntegerField(verbose_name='Ціна ($)')),
                ('mileage', models.CharField(max_length=30, verbose_name='Пробіг')),
                ('fuel', models.CharField(max_length=50, verbose_name='Тип пального / Двигун')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('image', models.URLField(blank=True, max_length=300, null=True, verbose_name='Посилання на фото')),
                ('transmission', models.CharField(default='Ручна / Механіка', max_length=50, verbose_name='Коробка передач')),
                ('color', models.CharField(default='Білий', max_length=50, verbose_name='Колір')),
                ('car_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Державний номер')),
                ('vin_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='VIN-код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис від власника')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='Посилання на додаткове фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myria.car')),
            ],
            options={
                'verbose_name': 'Додаткове photo',
                'verbose_name_plural': 'Додаткові фото',
            },
        ),
    ]
