# Generated by Django 6.0.5 on 2026-06-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Київ', 'Київ'), ('Вінниця', 'Вінниця'), ('Кропивницький', 'Кропивницький (Кіровоград)'), ('Полтава', 'Полтава'), ('Черкаси', 'Черкаси'), ('Тернопіль', 'Тернопіль'), ('Хмельницький', 'Хмельницький'), ('Львів', 'Львів'), ('Рівне', 'Рівне'), ('Івано-Франківськ', 'Івано-Франківськ'), ('Луцьк', 'Луцьк'), ('Ужгород', 'Ужгород'), ('Чернівці', 'Чернівці'), ('Харків', 'Харків'), ('Дніпро', 'Дніпро (Дніпропетровськ)'), ('Донецька обл.', 'Донецька обл.'), ('Запоріжжя', 'Запоріжжя'), ('Одеса', 'Одеса'), ('Миколаїв', 'Миколаїв'), ('Херсон', 'Херсон'), ('Житомир', 'Житомир'), ('Чернігів', 'Чернігів'), ('Суми', 'Суми')], max_length=50, verbose_name='Регіон')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='paintwork',
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_state',
        ),
        migrations.AddField(
            model_name='car',
            name='is_metallic',
            field=models.BooleanField(default=False, verbose_name='Металік'),
        ),
        migrations.AddField(
            model_name='car',
            name='paint_condition',
            field=models.CharField(choices=[('perfect', 'Як нове\nОригінальне лакофарбове покриття, без слідів користування та підфарбовувань'), ('repaired', "Професійно виправлені сліди використання\nНаприклад, повторне лакування, дрібний ремонт, рихтування невеликих вм'ятин"), ('not_repaired', "Невиправлені сліди використання\nНормальне зношення, наприклад, невеликі вм'ятини, подряпини лакофарбового покриття, сколи")], default='perfect', max_length=30, verbose_name='Лакофарбове покриття'),
        ),
        migrations.AddField(
            model_name='car',
            name='technical_condition',
            field=models.CharField(choices=[('perfect', 'Повністю непошкоджене\nПошкодження відсутні'), ('repaired', 'Професійно відремонтовані пошкодження\nПошкодження усунуті, не потребує ремонту'), ('damaged', 'Невідремонтовані пошкодження\nВнаслідок бойових дій чи ДТП, пошкодження кузова, несправність рульового управління, коробки передач, осей, сліди граду, тощо'), ('not_running', 'Не на ходу / На запчастини\nВнаслідок бойових дій, ДТП чи пожежі, несправності двигуна, тощо')], default='perfect', max_length=30, verbose_name='Технічний стан'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('beige', 'Бежевий'), ('black', 'Чорний'), ('blue', 'Синій'), ('brown', 'Коричневий'), ('green', 'Зелений'), ('grey', 'Сірий'), ('orange', 'Помаранчевий'), ('purple', 'Фолетовий'), ('red', 'Червоний'), ('white', 'Білий'), ('yellow', 'Жовтий')], default='white', max_length=20, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='myria.brand', verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myria.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='myria.region', verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='car',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myria.region', verbose_name='Регіон'),
        ),
    ]
